# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - run: mkdir -pvm 0700 ~/.ssh
      - run: echo "StrictHostKeyChecking=no" > ~/.ssh/config
      - run: echo "$CI_PRIVATE_RSA_KEY" > ~/.ssh/id_rsa
      - run: chmod 0400 ~/.ssh/id_rsa
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: git checkout $CIRCLE_BRANCH
      - run: git pull
      - run: git remote set-url --push origin $CI_SSH_REPO
      - run: yarn install
      - run: yarn lerna-version
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test:unit
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/lcov.info

  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            wsk property set --auth "$ADOBE_RUNTIME_AUTH" --apihost "$ADOBE_RUNTIME_HOST" --namespace "$ADOBE_NAMESPACE"
            yarn deploy

  publish:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: publish
          command: |
            lerna publish from-git --yes

workflows:
  version: 2
  build_deploy_publish:
    jobs:
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires:
            - build

